### ISSUE TITLE
Permissions for files created by the service

### ISSUE THREAD

**Issue by tiamat2012** [crowbarmaster/BedrockManagementService#10]
I am not sure if this is a bug or by design...

I have noticed that the folders/files created by the service (like files in the Server subfolder, but there are other folders too) cannot be opened in NotePad and saved easily.  You have to go into Folder or File properties, Security Tab, and add the user and explicitly grant rights to modify the files.  Since some of the client features are not 100% working, I have to edit the files directly to make some changes.  It's a fix-it-once problem, so the workaround is a few seconds to change the permissions.

This may be by (accidental) design.  Perhaps you would rather restrict these files like this so that the client really manages them?  If so, you can cancel/close this issue.  If you don't mind people making direct changes, then perhaps the permissions on create can be adjusted.

This could have also been because I initially ran the service in an Admin CMD prompt. Perhaps if I had run it as a normal user it would have set permissions to allow me to change the files.

**Comment by crowbarmaster** [comment]
So this is 100% by design. As you noted, running the service (or really, any executable) as Administrator will cause the files it writes to also be owned by Administrator. This is unfortunate for fast editing, however the easiest solution is to launch your editor as Admin, and it will then have no issues opening and saving the files. I prefer Notepad++ as it will ask you when it notices a protected file if you would like to relaunch as Admin, making it a fast solution. Also saves your changes without saving the file too, and that is handy!

**Comment by tiamat2012** [comment]
No problem.  Closing the issue.
