### ISSUE TITLE
Mojang license

### ISSUE THREAD

**Issue by tiamat2012** [crowbarmaster/BedrockManagementService#25]
I get the error:

"You have not accepted the license. Please visit the readme for more info!"

Even though I do manually set that field in the Globals.conf:

AcceptedMojangLic=true

Perhaps the keyword is not right?

**Comment by crowbarmaster** [comment]
Newest build fixes this issue! Actually the only way to pass was to turn it back off again. This check was re-written some time ago, and I never inversed the bool condition. Also this was moved somewhere it could totally interrupt startup, preventing exceptions that would otherwise have been thrown.

**Comment by tiamat2012** [comment]
2.56.8031.12492 no longer displays the message when set to true.  I didn't change it back to false.  I may try that later, but will still close this issue.
