### ISSUE TITLE
Build world_resource_packs.json to activate packs within world.

### ISSUE THREAD

**Issue by crowbarmaster** [crowbarmaster/BedrockManagementService#6]
If you create and maintain the world_resource_packs.json file with the right content in it in the right folder (same folder as the level.dat file), this will activate the various packs.  Otherwise, the Pack Manager really only gets you so far.  You could add a simple checkbox enable/disable editor for this file or simply enable all the packs that are installed on the server.  You can google to see how to create that file from the manifest.json data files in the packs.  It's a very simple json file.  I copied that file from a regular minecraft world where I activated the same 2 packs and it worked fine on the server to activate the packs.

_Part of a post originally posted by @tiamat2012 in https://github.com/crowbarmaster/BedrockManagementService/issues/2#issuecomment-988409823_

**Comment by tiamat2012** [comment]
BTW - there is also a world_behavior_packs.json to activate behavior packs.  It lives in the same folder and I believe it has the same format as the resource packs json file.

**Comment by crowbarmaster** [comment]
Structure and methods for writing these files has been written, and wrote the files as expected. I will need to work in managing this with pack removal too yet, so this may be a bit yet. Other issues exist here that I am currently working out first too, mostly due to the shift to .NET Core.

**Comment by tiamat2012** [comment]
I added 2 resource packs via the client and that worked fine.  The world_resource_packs.json was created correctly and activated both of the packs in the world.  I did not test the behavior json file creation as I don't have any of those types of packs.  I did not try to remove or change the installed packs, as your last comment says you are still working on that.  I think you don't necessarily have to remove the pack files from the server, just change the world_*_packs.json file to activate and deactivate a pack.  That way, people (and you) don't have to upload/reinstall anything.  I am thinking about those who may have a working pack and a new version of the same pack gets published, they can quickly deactivate the old and active the new, and be able to go back if the new one has problems.

I was able to open the R/B Pack Manager screen after they were installed, so that bug is also fixed.

**Comment by tiamat2012** [comment]
Removal of a pack deleted the pack files but did not update the world_resource_packs.json file.  So it's coming along... but not quite there yet.

**Comment by crowbarmaster** [comment]
Sounds like we are up to a working status here then! I hadn't thought of leaving pack files on the server and controlling enabling of packs. My current strategy involves parsing the package name into the folder name, so if the name remains the same there will be overwriting. I will need to look at an updated plugin before and after, does it get a new UUID I wonder? If so, I can use the UUID as a path, taking care of the issue. Otherwise I will have to timestamp the folders or similar to diversify the folder names. This will also require GUI adjustments to print the version in the listbox description along with the name, to avoid the risk having multiple versions with the exact name in the box, causing confusion and possible bugs. 

I will keep this open for now to ponder the scenario this presents, and a possible solution to make things work well.

**Comment by tiamat2012** [comment]
Yes it does get a new UUID and the version number will obviously change.  One of the packs I use got a minor number update and the UUID's were really close, so I forgot to change it when I updated the file manually (I only changed the version number) and it would not load.  And I had to take a hard look to see the UUID was ever so slightly different.

And yeah, the pack folder names may conflict - that might be a problem.  I think I read somewhere that pack folder names had to be insanely short (like 6 characters) for Xbox to work.  But so far, it works with the default names which are much longer than that on my Xbox.  So that length requirement may have been someone else's assumption because something didn't work for them and not a Microsoft/Mojang requirement.

**Comment by crowbarmaster** [comment]
Given this then, it would be possible to use the UUID for the pack folder then. I will perform manual testing to verify this week and see what happens! If it works I will draft a strategy in which we can opt to persist pack files. More thought is needed here, but it should be more than possible.

**Comment by tiamat2012** [comment]
I also don't know about the order that the server loads the packs.  In the minecraft on ipad, order does matter and the website to download packs some authors mention specific orders to load packs.  I wonder if the order they are listed in the world*.json files determines the order in the server.  The 2 packs I use don't really conflict with each other, but there are some packs that do.  You might have to split this off as another feature request and do some experimentation.  Also, as far as I know, there is no way to configure a plug-in on the server bedrock.  You can only do that on a mobile or windows minecraft version.  They would likely have to use a world editor or load the world on a mobile device, change it, then upload the world files to the server (the settings are likely stored in the minecraft database).
