### ISSUE TITLE
Backup testing at scale

### ISSUE THREAD

**Issue by tiamat2012** [crowbarmaster/BedrockManagementService#69]
The app needs to be tested at scale with a large bedrock world.  Think 16k x 16k 1.18 world or larger fully generated.  I can see where this could fail because of some assumptions made:

1) the pause command doesn’t return immediately with the list of files, (I think there are assumptions about returning the first time within a few seconds)

2) the list of returned files is very long and gets truncated or the read buffer gets overwhelmed or times out during the read (leaving data in the buffer)

3) that the backup memory stream consumes too much memory space and causes either significant Minecraft lag or even causes the server to run out of memory and things crash.

4) the backup could fail to write the whole backup due to out of disk space errors, which need to be handled gracefully

Unfortunately, I don’t have such a world for testing.   But you need one.  Perhaps someone knows of a way to get one created via an editor or world generator?

**Comment by tiamat2012** [comment]
We could also test that startup commands still work, or if Microsoft takes a lot longer to load/start a large world and the commands are sent before Minecraft is ready.

**Comment by crowbarmaster** [comment]
> The app needs to be tested at scale with a large bedrock world.  Think 16k x 16k 1.18 world or larger fully generated.  I can see where this could fail because of some assumptions made:
> 
> 1) the pause command doesn’t return immediately with the list of files, (I think there are assumptions about returning the first time within a few seconds)
> 
> 2) the list of returned files is very long and gets truncated or the read buffer gets overwhelmed or times out during the read (leaving data in the buffer)
> 
> 3) that the backup memory stream consumes too much memory space and causes either significant Minecraft lag or even causes the server to run out of memory and things crash.
> 
> 4) the backup could fail to write the whole backup due to out of disk space errors, which need to be handled gracefully
> 
> Unfortunately, I don’t have such a world for testing.   But you need one.  Perhaps someone knows of a way to get one created via an editor or world generator?

I fully agree with you! Actually I spent a hour or so teleport and chunk filling to make a world have some weight. 

No need to worry about the delay for the query, since I detect the query string itself, I'm not actually waiting for it, rather it is the trigger that starts the backup.

I can't say for sure, but some of the stacktraces are a single line and pretty huge. I would have to say it's safe to assume the query won't hurt it, but again, testing for it wouldn't hurt.

Memory usage: I agree could be an issue for a whole world; but mind you I only operate on on single file at a time, meaning this would only be an issue if the individual db files get to be large in size. I suppose a bit of research needs to be done to determine this possibility.

You're correct, there is not a user friendly way to notify the user of a failure specific to a lack of space. That being said, it shouldn't crash the service as I have an exception catch for IO issues here. I'll toss it on the list to add a way to notify the user of this failure!

Thanks again my friend. I wish you guys were around a while back. You can't possibly know what people would like to see without hearing it!

**Comment by crowbarmaster** [comment]
> We could also test that startup commands still work, or if Minecraft takes a lot longer to load/start a large world and the commands are sent before the server is ready.

This shouldn't be a problem either! I suppose I could give you a small bit of insight to this, since they are actually related by a method.

C# process redirects standard input to a stream for me, and I have set up an event handler to catch entire lines. The method behind this event handler has a handful of filters, and of these is one that looks for `INFO] Server started.` as well as looking for a string to contain the path `$@"{levelname}\db\"` to detect the save query. With this, I know that the server has started to the point where it is capable of receiving the commands. I do have a couple of larger maps that I use for testing (not quite the 16k you mentioned though), and all of that seems to work quite well!

**Comment by tiamat2012** [comment]
Sounds like you got it all covered then.  Have you ever seen the save query come back with a wait message, and ask you to try again?  It sounds like you can close this issue with no action needed.  If a server runs out of disk space, Minecraft and other problems will occur, so someone is going to notice.  You could just delete any partial backup files (which frees up a little space for the next step) and writes the exception to the service log and maybe a message within Minecraft for players to alert someone.

**Comment by crowbarmaster** [comment]
> Sounds like you got it all covered then. Have you ever seen the save query come back with a wait message, and ask you to try again? It sounds like you can close this issue with no action needed. If a server runs out of disk space, Minecraft and other problems will occur, so someone is going to notice. You could just delete any partial backup files (which frees up a little space for the next step) and writes the exception to the service log and maybe a message within Minecraft for players to alert someone.

I do watch for `A previous save has not been completed.`, in which triggers a one second delay before firing off the `save hold` command again. if that's not the message your referring to, and you have documentation or the exact phrase used in the message, I could add it pretty quickly! You touch base on another issue I have yet to open in the second part of your reply: Notifying players of server actions, in particular of an upcoming restart, and the ability to give players time to log off. I will open a new issue for this after I clean some of these current ones off the table!

**Comment by demifiend9** [comment]
@crowbarmaster Can you do one small thing please?

Send `say Backup started`  to server before save hold and `say Backup finished` after save resume so players would know when backup is made.

**Comment by crowbarmaster** [comment]
> @crowbarmaster Can you do one small thing please?
> 
> Send `say Backup started` to server before save hold and `say Backup finished` after save resume so players would know when backup is made.

That's a small and simple request, I will make sure it ships in the next update! This is in-line with a discussion in the directory topic. There will be much more to go along with this in the future, but I would like to clean up what we have going now before we get too much deeper into the pot 🤣

**Comment by crowbarmaster** [comment]
> > @crowbarmaster Can you do one small thing please?
> > Send `say Backup started` to server before save hold and `say Backup finished` after save resume so players would know when backup is made.
> 
> That's a small and simple request, I will make sure it ships in the next update! This is in-line with a discussion in the directory topic. There will be much more to go along with this in the future, but I would like to clean up what we have going now before we get too much deeper into the pot 🤣

This has been added! You will be happy to know that players will also be notified of failures too, allowing them to alert the admins!
![image](https://user-images.githubusercontent.com/69368213/152686796-90161ca8-4dd0-45b3-bced-f5969cf66940.png)

**Comment by crowbarmaster** [comment]
Further re-enforcements have been recently added to verify nothing here should be problematic! Closing issue! Thanks man!
