### ISSUE TITLE
Unable to stop first server in list

### ISSUE THREAD

**Issue by ElectronJunkie** [crowbarmaster/BedrockManagementService#79]
Not sure if this is by design, but I have noticed that the stop button is greyed out on the first server in the list when running multiple servers.

**Comment by tiamat2012** [comment]
It's by design because the first server always listens on the default ports regardless of what you have in the server config.  And if you stopped it and other servers, and restarted the wrong one first, you would have inconsistent results.

You can read more about it in Issue https://github.com/crowbarmaster/BedrockManagementService/issues/55

**Comment by crowbarmaster** [comment]
Thanks, @tiamat2012 !

I considered doing more for this to make it possible, however the overall outlook was a ton of work on my end to even attempt it further. I will be making a note of it in the readme to help users confirm this is a non-issue. Thanks for your support!

**Comment by ElectronJunkie** [comment]
That makes perfect sense! Guess I should have read down the issues a bit further >_<.
Curious if a simple fix for this would be to just have a "Phantom" Minecraft server running in the first position and somehow hide that from the user and local server browser?

Thanks for the quick replies CrowBarMaster and Tiamat2021!!!

**Comment by tiamat2012** [comment]
Unfortunately, people like me only have one bedrock server that listens on the default ports so my Xbox will connect to it on the local network, because of the network discovery mechanism forced on us my Microsoft.  You cannot enter a server name or port number in the Xbox version.

however, you can implement the simple fix right now and create a phantom server as your first server and then add your real servers and be able to start/stop them.
